// ─── Mock data for the import workflow ────────────────────────────────────────
// Realistic JAMB-style questions covering multiple years and status scenarios.
// This lets the UI render a complete, representative preview before the backend
// is wired up.

import type {
  ParsedQuestion,
  ParseSummary,
  ImportRecord,
} from "../types/import-types";

let _idCounter = 0;
function cid() {
  return `q_${++_idCounter}_${Math.random().toString(36).slice(2, 7)}`;
}

export const MOCK_QUESTIONS: ParsedQuestion[] = [
  // ── 2020 ──────────────────────────────────────────────────────────────────
  {
    _clientId: "q_2020_01",
    rowIndex: 1,
    year: 2020,
    subject: "Accountancy",
    text: "Which of the following is NOT a characteristic of a sole proprietorship?",
    options: [
      { key: "A", text: "Single ownership" },
      { key: "B", text: "Unlimited liability" },
      { key: "C", text: "Separate legal entity" },
      { key: "D", text: "Ease of formation" },
    ],
    answer: "C",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2020_02",
    rowIndex: 2,
    year: 2020,
    subject: "Accountancy",
    text: "The accounting equation states that Assets = Liabilities + ______",
    options: [
      { key: "A", text: "Expenses" },
      { key: "B", text: "Revenue" },
      { key: "C", text: "Owner's Equity" },
      { key: "D", text: "Capital Expenditure" },
    ],
    answer: "C",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2020_03",
    rowIndex: 3,
    year: 2020,
    subject: "Accountancy",
    text: "Depreciation is best described as the allocation of the cost of a tangible asset over its useful life.",
    options: [
      { key: "A", text: "True" },
      { key: "B", text: "False" },
      { key: "C", text: "Partially true" },
      { key: "D", text: "Cannot be determined" },
    ],
    answer: "A",
    status: "warning",
    statusReason:
      "Options B, C, D are non-standard for a multiple-choice format",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2020_04",
    rowIndex: 4,
    year: 2020,
    subject: "Accountancy",
    text: "Which document is prepared to record all bank transactions?",
    options: [
      { key: "A", text: "Cash book" },
      { key: "B", text: "Bank statement" },
      { key: "C", text: "Bank reconciliation statement" },
      { key: "D", text: "Trial balance" },
    ],
    answer: "C",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2020_05",
    rowIndex: 5,
    year: 2020,
    subject: "Accountancy",
    text: "A business buys goods on credit for ₦50,000. How does this affect the accounting equation?",
    options: [
      { key: "A", text: "Assets increase, owner's equity decreases" },
      { key: "B", text: "Assets increase, liabilities increase" },
      { key: "C", text: "Assets decrease, liabilities decrease" },
      { key: "D", text: "Owner's equity increases, liabilities increase" },
    ],
    answer: "B",
    status: "valid",
    hasImage: false,
    image: null,
  },

  // ── 2021 ──────────────────────────────────────────────────────────────────
  {
    _clientId: "q_2021_01",
    rowIndex: 6,
    year: 2021,
    subject: "Accountancy",
    text: "Which of the following is NOT a current asset?",
    options: [
      { key: "A", text: "Cash" },
      { key: "B", text: "Debtors" },
      { key: "C", text: "Prepaid expenses" },
      { key: "D", text: "Plant and machinery" },
    ],
    answer: "D",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2021_02",
    rowIndex: 7,
    year: 2021,
    subject: "Accountancy",
    text: "Which of the following is NOT a characteristic of a sole proprietorship?",
    options: [
      { key: "A", text: "Single ownership" },
      { key: "B", text: "Unlimited liability" },
      { key: "C", text: "Separate legal entity" },
      { key: "D", text: "Ease of formation" },
    ],
    answer: "C",
    status: "duplicate",
    statusReason: "Question text closely matches row 1 (2020)",
    possibleDuplicateOf: "q_2020_01",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2021_03",
    rowIndex: 8,
    year: 2021,
    subject: "Accountancy",
    text: "The prime cost of production includes",
    options: [
      { key: "A", text: "Direct materials + Direct labour" },
      { key: "B", text: "Direct materials + Overhead" },
      { key: "C", text: "Overhead + Profit" },
      { key: "D", text: "Selling expenses + Admin expenses" },
    ],
    answer: "A",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2021_04",
    rowIndex: 9,
    year: 2021,
    subject: "Accountancy",
    text: "",
    options: [
      { key: "A", text: "First option" },
      { key: "B", text: "Second option" },
      { key: "C", text: "Third option" },
      { key: "D", text: "Fourth option" },
    ],
    answer: "A",
    status: "error",
    statusReason: "Missing question text",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2021_05",
    rowIndex: 10,
    year: 2021,
    subject: "Accountancy",
    text: "Bad debts are debts that are unlikely to be collected and are written off as an expense.",
    options: [
      { key: "A", text: "Recorded in the sales day book" },
      { key: "B", text: "Written off to the profit and loss account" },
      { key: "C", text: "Carried forward as an asset" },
      { key: "D", text: "Deducted from purchases" },
    ],
    answer: "B",
    status: "valid",
    hasImage: false,
    image: null,
  },

  // ── 2022 ──────────────────────────────────────────────────────────────────
  {
    _clientId: "q_2022_01",
    rowIndex: 11,
    year: 2022,
    subject: "Accountancy",
    text: "Which of the following correctly describes the purpose of a trial balance?",
    options: [
      { key: "A", text: "To check the arithmetic accuracy of the books" },
      { key: "B", text: "To calculate profits" },
      { key: "C", text: "To prepare the cash flow statement" },
      { key: "D", text: "To audit the accounts" },
    ],
    answer: "A",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2022_02",
    rowIndex: 12,
    year: 2022,
    subject: "Accountancy",
    text: "The formula for calculating the rate of stock turnover is",
    options: [
      { key: "A", text: "Cost of sales / Average stock" },
      { key: "B", text: "Net profit / Sales × 100" },
      { key: "C", text: "Gross profit / Cost of sales × 100" },
      { key: "D", text: "Sales / Total assets" },
    ],
    answer: "A",
    status: "valid",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2022_03",
    rowIndex: 13,
    year: 2022,
    subject: "Accountancy",
    text: "Accrued expenses are",
    options: [
      { key: "A", text: "Expenses paid in advance" },
      { key: "B", text: "Expenses incurred but not yet paid" },
      { key: "C", text: "Revenue received in advance" },
      { key: "D", text: "Revenue earned but not yet received" },
    ],
    answer: null,
    status: "error",
    statusReason: "Missing correct answer",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2022_04",
    rowIndex: 14,
    year: 2022,
    subject: "Accountancy",
    text: "The accounting equation states that Assets = Liabilities + ______",
    options: [
      { key: "A", text: "Expenses" },
      { key: "B", text: "Revenue" },
      { key: "C", text: "Owner's Equity" },
      { key: "D", text: "Capital Expenditure" },
    ],
    answer: "C",
    status: "duplicate",
    statusReason: "Question text closely matches row 2 (2020)",
    possibleDuplicateOf: "q_2020_02",
    hasImage: false,
    image: null,
  },
  {
    _clientId: "q_2022_05",
    rowIndex: 15,
    year: 2022,
    subject: "Accountancy",
    text: "The profit and loss account is used to determine the",
    options: [
      { key: "A", text: "Financial position of the business" },
      { key: "B", text: "Net profit or loss for the period" },
      { key: "C", text: "Cash position of the business" },
      { key: "D", text: "Capital structure of the business" },
    ],
    answer: "B",
    status: "valid",
    hasImage: false,
    image: null,
  },
];

export const MOCK_SUMMARY: ParseSummary = {
  totalRows: 15,
  totalQuestions: 15,
  years: [2020, 2021, 2022],
  validCount: 10,
  warningCount: 1,
  errorCount: 2,
  duplicateCount: 2,
  contextRowCount: 0,
};

export const MOCK_IMPORT_RECORDS: ImportRecord[] = [
  {
    id: "imp_001",
    subject: "Accountancy",
    format: "xlsx",
    filename: "Accountancy.xlsx",
    status: "Needs Review",
    questionCount: 150,
    years: [2020, 2021, 2022],
    validCount: 140,
    warningCount: 5,
    errorCount: 3,
    duplicateCount: 2,
    submittedBy: "admin@drpass.ng",
    createdAt: "2026-08-15T10:32:00Z",
    questions: MOCK_QUESTIONS,
  },
  {
    id: "imp_002",
    subject: "Mathematics",
    format: "json",
    filename: "Mathematics_2019-2023.json",
    status: "Submitted",
    questionCount: 250,
    years: [2019, 2020, 2021, 2022, 2023],
    validCount: 245,
    warningCount: 4,
    errorCount: 1,
    duplicateCount: 0,
    submittedBy: "editor@drpass.ng",
    createdAt: "2026-08-14T08:15:00Z",
    questions: MOCK_QUESTIONS,
  },
  {
    id: "imp_003",
    subject: "English Language",
    format: "xlsx",
    filename: "English_UTME.xlsx",
    status: "Approved",
    questionCount: 200,
    years: [2018, 2019, 2020, 2021],
    validCount: 200,
    warningCount: 0,
    errorCount: 0,
    duplicateCount: 0,
    submittedBy: "admin@drpass.ng",
    createdAt: "2026-08-10T14:00:00Z",
    questions: MOCK_QUESTIONS,
  },
];

export function getMockImportRecord(id: string): ImportRecord | undefined {
  return MOCK_IMPORT_RECORDS.find((r) => r.id === id);
}
